root: true
extends:
  - '@sachinahya/myconfig/typescript'
  - '@sachinahya/myconfig/typescript-type-checking'
rules:
  no-return-await: error
  sonarjs/cognitive-complexity: warn
  # TODO: Consider enabling some of these
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-return': off
  '@typescript-eslint/restrict-plus-operands': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/unbound-method': off

overrides:
  # Client TypeScript files
  - files: packages/client/**/*.ts?(x)
    extends:
      - '@sachinahya/myconfig/react'
    rules:
      'react/jsx-uses-react': off
      'react/react-in-jsx-scope': off
      '@typescript-eslint/no-unused-vars':
        - warn
        - varsIgnorePattern: _(QUERY|MUTATION|FRAGMENT)$
          ignoreRestSiblings: true
  # graphql-codegen output
  - files: packages/client/**/?(*.)gql.ts
    rules:
      '@typescript-eslint/no-unused-vars': off
      jsdoc/require-returns: off
  # Resolvers
  - files: packages/server/src/?(entities|resolvers)/**/*.ts
    rules:
      '@typescript-eslint/no-unused-vars':
        - warn
        - argsIgnorePattern: ^(of|type|returns)$
          ignoreRestSiblings: true
