packageExtensions:
  apollo-reporting-protobuf@*:
    dependencies:
      '@types/long': '*'
      long: '*'
  subscriptions-transport-ws@*:
    dependencies:
      '@types/ws': '*'
  winston-transport@*:
    dependencies:
      logform: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-berry.cjs
