root: true
extends:
  - '@sachinahya/myconfig/typescript'
  - '@sachinahya/myconfig/typescript-type-checking'
rules:
  no-return-await: error
overrides:
  - files: src/?(entities|resolvers)/**/*.ts
    rules:
      '@typescript-eslint/no-unused-vars':
        - warn
        - argsIgnorePattern: ^(of|type|returns)$
